### ISSUE TITLE
Key generation

### ISSUE THREAD

**Issue by r-neisse** [privacybydesign/irma-demo-schememanager#2]
Hi,
Is there a way to generate credentials directly in Java without irmatool or silvia_keygen?
Thank you,
Ricardo

**Comment by sietseringers** [comment]
Hi Ricardo,

Unfortunately not. An Idemix public/private keypair consists of (among other things) a pair of safe primes, i.e., primes such that `(prime-1)/2` is also prime. Generating such special primes takes prohibitively long in Java; irmatool and silvia_keygen both use `openssl` which is much faster.

Can you tell me a little about why it must be in Java?

**Comment by r-neisse** [comment]
Hi,
We don't have any special requirement for Java, it is just for convenience to avoid having to build irmatool or silvia_keygen  separately since all the other code/libraries we are experimenting with are in Java. Thank you for the reply!
Ricardo
